import unittest

import pytest

from opf_parser.opf_parser import OPFParser

HAS_EXT_LIB = '''
<?xml version='1.0' encoding='utf-8'?>
<package xmlns="http://www.idpf.org/2007/opf" unique-identifier="uuid_id" version="2.0">
    <metadata xmlns:dc="http://purl.org/dc/elements/1.1/" xmlns:opf="http://www.idpf.org/2007/opf">
        <dc:identifier opf:scheme="calibre" id="calibre_id">34007</dc:identifier>
        <dc:identifier opf:scheme="uuid" id="uuid_id">c8882df2-2680-4c9c-b783-6250c7754b74</dc:identifier>
        <dc:title>Incredible Hulk Epic Collection, Volume 6: Crisis On Counter-Earth</dc:title>
        <dc:creator opf:file-as="Goodwin, Archie &amp; Claremont, Chris &amp; Conway, Gerry &amp; Thomas, Roy &amp; Englehart, Steve &amp; Gerber, Steve &amp; Isabella, Tony" opf:role="aut">Archie Goodwin</dc:creator>
        <dc:creator opf:file-as="Goodwin, Archie &amp; Claremont, Chris &amp; Conway, Gerry &amp; Thomas, Roy &amp; Englehart, Steve &amp; Gerber, Steve &amp; Isabella, Tony" opf:role="aut">Chris Claremont</dc:creator>
        <dc:creator opf:file-as="Goodwin, Archie &amp; Claremont, Chris &amp; Conway, Gerry &amp; Thomas, Roy &amp; Englehart, Steve &amp; Gerber, Steve &amp; Isabella, Tony" opf:role="aut">Gerry Conway</dc:creator>
        <dc:creator opf:file-as="Goodwin, Archie &amp; Claremont, Chris &amp; Conway, Gerry &amp; Thomas, Roy &amp; Englehart, Steve &amp; Gerber, Steve &amp; Isabella, Tony" opf:role="aut">Roy Thomas</dc:creator>
        <dc:creator opf:file-as="Goodwin, Archie &amp; Claremont, Chris &amp; Conway, Gerry &amp; Thomas, Roy &amp; Englehart, Steve &amp; Gerber, Steve &amp; Isabella, Tony" opf:role="aut">Steve Englehart</dc:creator>
        <dc:creator opf:file-as="Goodwin, Archie &amp; Claremont, Chris &amp; Conway, Gerry &amp; Thomas, Roy &amp; Englehart, Steve &amp; Gerber, Steve &amp; Isabella, Tony" opf:role="aut">Steve Gerber</dc:creator>
        <dc:creator opf:file-as="Goodwin, Archie &amp; Claremont, Chris &amp; Conway, Gerry &amp; Thomas, Roy &amp; Englehart, Steve &amp; Gerber, Steve &amp; Isabella, Tony" opf:role="aut">Tony Isabella</dc:creator>
        <dc:contributor opf:file-as="calibre" opf:role="bkp">calibre (7.20.0) [https://calibre-ebook.com]</dc:contributor>
        <dc:date>2021-09-15T00:00:00+00:00</dc:date>
        <dc:description>Hulk takes a trip to Counter-Earth, where he confronts his most-hated enemy: Bruce Banner! Add in the Rhino and the Abomination, and the action and drama can't be contained! Then, the Hulk heads north to Canada - where the X-Men's Mimic returns, and the Wendigo makes its debut! And the drama continues when Betty Ross is mutated into the Harpy! Next, the green goliath sets out on a path of revenge against a murderer's row of earth-shaking enemies - including Juggernaut, Cobalt Man and a second encounter with Rhino and Abomination! Finally, the Hulk lands in Attilan, where the Inhumans are forced to launch him into outer space to prevent the destruction of their home. But where the Hulk lands will surprise him - and a cosmic saga alongside the messianic Adam Warlock awaits!

Collects Incredible Hulk (1968) #157-178; material from FOOM (1973) #1-2.</dc:description>
        <dc:publisher>Marvel</dc:publisher>
        <dc:language>en</dc:language>
        <meta name="calibre:series" content="Incredible Hulk Epic Collection"/>
        <meta name="calibre:series_index" content="6"/>
        <meta name="calibre:timestamp" content="2025-03-21T19:36:08+00:00"/>
        <meta name="calibre:title_sort" content="Incredible Hulk Epic Collection, Volume 6: Crisis On Counter-Earth"/>
        <meta name="calibre:user_metadata:#age_rating" content="{&quot;table&quot;: &quot;custom_column_17&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;enumeration&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Age Rating&quot;, &quot;search_terms&quot;: [&quot;#age_rating&quot;], &quot;label&quot;: &quot;age_rating&quot;, &quot;colnum&quot;: 17, &quot;display&quot;: {&quot;enum_values&quot;: [&quot;General&quot;, &quot;Teen (13+)&quot;, &quot;14&quot;, &quot;YA (16+)&quot;, &quot;Adult&quot;], &quot;enum_colors&quot;: [], &quot;use_decorations&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 22, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#archive_reason" content="{&quot;table&quot;: &quot;custom_column_1&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;enumeration&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Archive Reason&quot;, &quot;search_terms&quot;: [&quot;#archive_reason&quot;], &quot;label&quot;: &quot;archive_reason&quot;, &quot;colnum&quot;: 1, &quot;display&quot;: {&quot;enum_values&quot;: [&quot;Better Version Exists&quot;, &quot;Old Ebook Version&quot;, &quot;Split into Parts&quot;, &quot;Contained in Collection&quot;], &quot;enum_colors&quot;: [], &quot;use_decorations&quot;: 0, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 23, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#collections" content="{&quot;table&quot;: &quot;custom_column_2&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: &quot;|&quot;, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Collections&quot;, &quot;search_terms&quot;: [&quot;#collections&quot;], &quot;label&quot;: &quot;collections&quot;, &quot;colnum&quot;: 2, &quot;display&quot;: {&quot;description&quot;: &quot;&quot;, &quot;is_names&quot;: false}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 24, &quot;#value#&quot;: [], &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {&quot;cache_to_list&quot;: &quot;|&quot;, &quot;ui_to_list&quot;: &quot;,&quot;, &quot;list_to_ui&quot;: &quot;, &quot;}}"/>
        <meta name="calibre:user_metadata:#comic_volume" content="{&quot;table&quot;: &quot;custom_column_16&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Comic Volume&quot;, &quot;search_terms&quot;: [&quot;#comic_volume&quot;], &quot;label&quot;: &quot;comic_volume&quot;, &quot;colnum&quot;: 16, &quot;display&quot;: {&quot;use_decorations&quot;: 0, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 25, &quot;#value#&quot;: &quot;2021&quot;, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#comicvine_link" content="{&quot;table&quot;: &quot;custom_column_24&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;comments&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Comicvine Link&quot;, &quot;search_terms&quot;: [&quot;#comicvine_link&quot;], &quot;label&quot;: &quot;comicvine_link&quot;, &quot;colnum&quot;: 24, &quot;display&quot;: {&quot;heading_position&quot;: &quot;hide&quot;, &quot;interpret_as&quot;: &quot;short-text&quot;, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 26, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#dateread" content="{&quot;table&quot;: &quot;custom_column_3&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;datetime&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Date Read&quot;, &quot;search_terms&quot;: [&quot;#dateread&quot;], &quot;label&quot;: &quot;dateread&quot;, &quot;colnum&quot;: 3, &quot;display&quot;: {&quot;date_format&quot;: null}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 27, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#drm" content="{&quot;table&quot;: &quot;custom_column_15&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;bool&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;DRM?&quot;, &quot;search_terms&quot;: [&quot;#drm&quot;], &quot;label&quot;: &quot;drm&quot;, &quot;colnum&quot;: 15, &quot;display&quot;: {&quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 28, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#ext_library" content="{&quot;table&quot;: &quot;custom_column_26&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: &quot;|&quot;, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;External Library&quot;, &quot;search_terms&quot;: [&quot;#ext_library&quot;], &quot;label&quot;: &quot;ext_library&quot;, &quot;colnum&quot;: 26, &quot;display&quot;: {&quot;is_names&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 29, &quot;#value#&quot;: [&quot;test-ext-lib&quot;], &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {&quot;cache_to_list&quot;: &quot;|&quot;, &quot;ui_to_list&quot;: &quot;,&quot;, &quot;list_to_ui&quot;: &quot;, &quot;}}"/>
        <meta name="calibre:user_metadata:#flesch_kincaid" content="{&quot;table&quot;: &quot;custom_column_4&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;int&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Flesch-Kincaid&quot;, &quot;search_terms&quot;: [&quot;#flesch_kincaid&quot;], &quot;label&quot;: &quot;flesch_kincaid&quot;, &quot;colnum&quot;: 4, &quot;display&quot;: {&quot;number_format&quot;: null, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 30, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#flesch_kincaid_ease" content="{&quot;table&quot;: &quot;custom_column_5&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;int&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Flesch-Kincaid Reading Ease&quot;, &quot;search_terms&quot;: [&quot;#flesch_kincaid_ease&quot;], &quot;label&quot;: &quot;flesch_kincaid_ease&quot;, &quot;colnum&quot;: 5, &quot;display&quot;: {&quot;description&quot;: &quot;&quot;, &quot;number_format&quot;: null}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 31, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#genre" content="{&quot;table&quot;: &quot;custom_column_6&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: &quot;|&quot;, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Genre&quot;, &quot;search_terms&quot;: [&quot;#genre&quot;], &quot;label&quot;: &quot;genre&quot;, &quot;colnum&quot;: 6, &quot;display&quot;: {&quot;is_names&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 32, &quot;#value#&quot;: [], &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {&quot;cache_to_list&quot;: &quot;|&quot;, &quot;ui_to_list&quot;: &quot;,&quot;, &quot;list_to_ui&quot;: &quot;, &quot;}}"/>
        <meta name="calibre:user_metadata:#gunning_fog" content="{&quot;table&quot;: &quot;custom_column_7&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;int&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Gunning Fog Index&quot;, &quot;search_terms&quot;: [&quot;#gunning_fog&quot;], &quot;label&quot;: &quot;gunning_fog&quot;, &quot;colnum&quot;: 7, &quot;display&quot;: {&quot;number_format&quot;: null, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 33, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#importedkindlecollections" content="{&quot;table&quot;: &quot;custom_column_8&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: &quot;|&quot;, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Imported Kindle Collections&quot;, &quot;search_terms&quot;: [&quot;#importedkindlecollections&quot;], &quot;label&quot;: &quot;importedkindlecollections&quot;, &quot;colnum&quot;: 8, &quot;display&quot;: {&quot;is_names&quot;: false}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 34, &quot;#value#&quot;: [], &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {&quot;cache_to_list&quot;: &quot;|&quot;, &quot;ui_to_list&quot;: &quot;,&quot;, &quot;list_to_ui&quot;: &quot;, &quot;}}"/>
        <meta name="calibre:user_metadata:#ko_last_location" content="{&quot;table&quot;: &quot;custom_column_18&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;KO Last Location&quot;, &quot;search_terms&quot;: [&quot;#ko_last_location&quot;], &quot;label&quot;: &quot;ko_last_location&quot;, &quot;colnum&quot;: 18, &quot;display&quot;: {&quot;use_decorations&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 35, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#ko_percent_read" content="{&quot;table&quot;: &quot;custom_column_19&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;float&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;KO Percent Read&quot;, &quot;search_terms&quot;: [&quot;#ko_percent_read&quot;], &quot;label&quot;: &quot;ko_percent_read&quot;, &quot;colnum&quot;: 19, &quot;display&quot;: {&quot;number_format&quot;: &quot;{:.0%}&quot;, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 36, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#ko_rating" content="{&quot;table&quot;: &quot;custom_column_20&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;rating&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;KO Rating&quot;, &quot;search_terms&quot;: [&quot;#ko_rating&quot;], &quot;label&quot;: &quot;ko_rating&quot;, &quot;colnum&quot;: 20, &quot;display&quot;: {&quot;allow_half_stars&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 37, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#ko_reading_status" content="{&quot;table&quot;: &quot;custom_column_21&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;KO Reading Status&quot;, &quot;search_terms&quot;: [&quot;#ko_reading_status&quot;], &quot;label&quot;: &quot;ko_reading_status&quot;, &quot;colnum&quot;: 21, &quot;display&quot;: {&quot;use_decorations&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 38, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#pages" content="{&quot;table&quot;: &quot;custom_column_9&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;int&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Pages&quot;, &quot;search_terms&quot;: [&quot;#pages&quot;], &quot;label&quot;: &quot;pages&quot;, &quot;colnum&quot;: 9, &quot;display&quot;: {&quot;number_format&quot;: &quot;{0:,}&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 39, &quot;#value#&quot;: 474, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#rating_thomas" content="{&quot;table&quot;: &quot;custom_column_22&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;rating&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Rating (Thomas)&quot;, &quot;search_terms&quot;: [&quot;#rating_thomas&quot;], &quot;label&quot;: &quot;rating_thomas&quot;, &quot;colnum&quot;: 22, &quot;display&quot;: {&quot;allow_half_stars&quot;: true, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 40, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#read" content="{&quot;table&quot;: &quot;custom_column_10&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;bool&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Read&quot;, &quot;search_terms&quot;: [&quot;#read&quot;], &quot;label&quot;: &quot;read&quot;, &quot;colnum&quot;: 10, &quot;display&quot;: {}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 41, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#source" content="{&quot;table&quot;: &quot;custom_column_11&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;text&quot;, &quot;is_multiple&quot;: &quot;|&quot;, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Source&quot;, &quot;search_terms&quot;: [&quot;#source&quot;], &quot;label&quot;: &quot;source&quot;, &quot;colnum&quot;: 11, &quot;display&quot;: {&quot;is_names&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 42, &quot;#value#&quot;: [&quot;Mylar&quot;], &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {&quot;cache_to_list&quot;: &quot;|&quot;, &quot;ui_to_list&quot;: &quot;,&quot;, &quot;list_to_ui&quot;: &quot;, &quot;}}"/>
        <meta name="calibre:user_metadata:#story_arc" content="{&quot;table&quot;: &quot;custom_column_12&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;series&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Story Arc&quot;, &quot;search_terms&quot;: [&quot;#story_arc&quot;], &quot;label&quot;: &quot;story_arc&quot;, &quot;colnum&quot;: 12, &quot;display&quot;: {}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 43, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#type" content="{&quot;table&quot;: &quot;custom_column_13&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;enumeration&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Type&quot;, &quot;search_terms&quot;: [&quot;#type&quot;], &quot;label&quot;: &quot;type&quot;, &quot;colnum&quot;: 13, &quot;display&quot;: {&quot;enum_values&quot;: [&quot;Book&quot;, &quot;Comic Collection&quot;, &quot;Magazine&quot;, &quot;Game&quot;, &quot;Manga&quot;, &quot;Single Issue Comic&quot;], &quot;enum_colors&quot;: [], &quot;use_decorations&quot;: false, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: true, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 45, &quot;#value#&quot;: &quot;Comic Collection&quot;, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
        <meta name="calibre:user_metadata:#words" content="{&quot;table&quot;: &quot;custom_column_14&quot;, &quot;column&quot;: &quot;value&quot;, &quot;datatype&quot;: &quot;int&quot;, &quot;is_multiple&quot;: null, &quot;kind&quot;: &quot;field&quot;, &quot;name&quot;: &quot;Words&quot;, &quot;search_terms&quot;: [&quot;#words&quot;], &quot;label&quot;: &quot;words&quot;, &quot;colnum&quot;: 14, &quot;display&quot;: {&quot;number_format&quot;: null, &quot;description&quot;: &quot;&quot;}, &quot;is_custom&quot;: true, &quot;is_category&quot;: false, &quot;link_column&quot;: &quot;value&quot;, &quot;category_sort&quot;: &quot;value&quot;, &quot;is_csp&quot;: false, &quot;is_editable&quot;: true, &quot;rec_index&quot;: 46, &quot;#value#&quot;: null, &quot;#extra#&quot;: null, &quot;is_multiple2&quot;: {}}"/>
    </metadata>
    <guide>
        <reference type="cover" title="Cover" href="cover.jpg"/>
    </guide>
</package>
'''


@pytest.mark.parametrize("contents, ext_lib, result", [
    (None, None, False),
    ('', None, False),
    ('None', None, False),
    (HAS_EXT_LIB, 'test-ext-lib', True),
    (HAS_EXT_LIB, 'test-ext-lib-blork', False),
])
def test_base_parsing(contents, ext_lib, result):
    parser = OPFParser()
    assert parser.in_ext_lib(contents, ext_lib) == result
